<a href="https://colab.research.google.com/github/antonio2505/SuperDataSience_Projects_DL/blob/main/Word_Embeded_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## the sentence
sent = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
    

In [3]:
sent

['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better.']

In [4]:
##vocabulary size
voc_size = 10000

In [5]:
##One Hot Representation
one_hot_rep = [one_hot(word,voc_size) for word in sent]
print(one_hot_rep)

[[4085, 8133], [4582, 3604], [1567, 2518], [9671, 3604], [3617], [1075], [4993, 2518], [8018, 4582], [4993, 3604], [848, 9286, 8133, 8626]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embeded_doc = pad_sequences(one_hot_rep,padding='pre', maxlen=sent_length)
print(embeded_doc)

[[   0    0    0    0    0    0 4085 8133]
 [   0    0    0    0    0    0 4582 3604]
 [   0    0    0    0    0    0 1567 2518]
 [   0    0    0    0    0    0 9671 3604]
 [   0    0    0    0    0    0    0 3617]
 [   0    0    0    0    0    0    0 1075]
 [   0    0    0    0    0    0 4993 2518]
 [   0    0    0    0    0    0 8018 4582]
 [   0    0    0    0    0    0 4993 3604]
 [   0    0    0    0  848 9286 8133 8626]]


In [9]:
dim=10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
embeded_doc[0]

array([   0,    0,    0,    0,    0,    0, 4085, 8133], dtype=int32)

In [14]:
print(model.predict(embeded_doc))

[[[ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0395555   0.00744253 -0.02533733 -0.04983573  0.01194652
    0.0195449  -0.04347043  0.04571715  0.0191054   0.02028893]
  [ 0.0214283  -0.02839592  0.04413499  0.00024568 -0.02164221
    0.04296399 -0.01052133  0.04390246 -0.04637691  0.03305909]
  [ 0.0273605  -0.03956759 -0.00745257  0.01395103  0.01484789
    0.035944   -0.00888684  0.04300579  0.018323